# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b263b676e4f4e685af326b43d882f560a9deded4a7be951a73a98f57dbb8920d51facd8f413458f00d4f269c6c8ac42551f4440c75250531c9721c9249abeb2c

test:
  secret_key_base: 7a5e840bfaa77e8102c324b1cfdd519c5ac350d7ac93d6d549188d9d83e309c058dbaa31401a3839f34e292a53ce807f28962740d24de192224d27bdc901a928

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
